image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Activate Conda Environment
    init: >
        conda_env_name=variant_calling
        if [ ! -d /workspace/miniconda ]; then
            echo "Installing Miniconda...";
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
            bash miniconda.sh -b -p /workspace/miniconda;
            rm miniconda.sh;
            echo "Miniconda installed.";
        fi;
        /workspace/miniconda/bin/conda init bash # init again due to potential gitpod override of Docker state
        echo "PATH=/workspace/miniconda/bin:$PATH" >> $HOME/.bashrc;
        echo "conda activate $conda_env_name" >> $HOME/.bashrc;
        source $HOME/.bashrc;
        conda config --set auto_activate_base false;
        echo "Creating Conda Environment...";
        conda env create -f environment.yml || conda env update -f environment.yml;
    command: echo "Activating Conda Environment..." && conda activate $conda_env_name



ports:
  - port: 8888
    onOpen: open-preview